In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import os 

working_dir = os.getcwd()
print(working_dir)

/Users/alvinqin/Springboard_ds/Springboard/Capstone Two: Data Wrangling

In [9]:
#Load the data

train = pd.read_csv('../volcanic_data/train.csv')
train.info()
train.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4431 entries, 0 to 4430
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   segment_id        4431 non-null   int64
 1   time_to_eruption  4431 non-null   int64
dtypes: int64(2)
memory usage: 69.4 KB

   segment_id  time_to_eruption
0  1136037770          12262005
1  1969647810          32739612
2  1895879680          14965999
3  2068207140          26469720
4   192955606          31072429

In [14]:
sample_submission = pd.read_csv('../volcanic_data/sample_submission.csv')
sample_submission.info()
sample_submission.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4520 entries, 0 to 4519
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   segment_id        4520 non-null   int64
 1   time_to_eruption  4520 non-null   int64
dtypes: int64(2)
memory usage: 70.8 KB

   segment_id  time_to_eruption
0  1000213997                 0
1   100023368                 0
2  1000488999                 0
3  1001028887                 0
4  1001857862                 0

In [11]:
data = train.copy()

In [12]:
# making segments data into one data frame
def make_data():
    global data
    n = 0
    for  i in data.segment_id :
        file = pd.read_csv('../volcanic_data/train/{}.csv'.format(i))
        for x in file.columns:
            data.loc[n:n+1,x+'_mean'] = file[x].mean()
            data.loc[n,x+'_std'] = file[x].std()
            data.loc[n,x+'_min'] = file[x].min()
            data.loc[n,x+'_20'] = file[x].quantile(0.20)
            data.loc[n,x+'_40'] = file[x].quantile(0.40)
            data.loc[n,x+'_50'] = file[x].quantile(0.50)
            data.loc[n,x+'_60'] = file[x].quantile(0.60)
            data.loc[n,x+'_80'] = file[x].quantile(0.80)
            data.loc[n,x+'_max'] = file[x].max()
        n +=1

    data.fillna(0,inplace=True)
    return data
make_data()

,segment_id,time_to_eruption,sensor_1_mean,sensor_1_std,sensor_1_min,sensor_1_20,sensor_1_40,sensor_1_50,sensor_1_60,sensor_1_80,...,sensor_9_max,sensor_10_mean,sensor_10_std,sensor_10_min,sensor_10_20,sensor_10_40,sensor_10_50,sensor_10_60,sensor_10_80,sensor_10_max
0,1136037770,12262005,-1.610323,303.096099,-1421.0,-249.0,-72.0,0.0,72.0,249.0,...,2021.0,2.599440,596.865818,-3527.0,-503.0,-151.0,0.0,159.0,507.0,2187.0
1,1969647810,32739612,1.426126,438.360560,-2005.0,-333.0,-96.0,0.0,100.0,338.0,...,2189.0,19.895518,932.699662,-4591.0,-692.0,-202.0,0.0,205.0,710.0,5319.0
2,1895879680,14965999,2.504592,241.575415,-1115.0,-195.0,-58.0,0.0,58.0,199.0,...,1778.0,0.968101,500.544892,-2798.0,-402.0,-121.0,0.0,120.0,403.0,2522.0
3,2068207140,26469720,2.165797,221.967825,-1025.0,-171.0,-50.0,0.0,52.0,177.0,...,1340.0,8.381444,523.449843,-2911.0,-400.0,-121.0,0.0,122.0,407.0,3614.0
4,192955606,31072429,0.073815,261.695935,-1190.0,-216.0,-63.0,0.0,62.0,212.0,...,7725.0,-3.740471,562.748316,-2611.0,-458.0,-134.0,0.0,134.0,449.0,3274.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4426,873340274,15695097,0.906735,613.427301,-2610.0,-511.0,-155.0,0.0,155.0,518.0,...,3085.0,-3.377394,1053.539787,-5726.0,-839.0,-249.0,0.0,240.0,838.0,5493.0
4427,1297437712,35659379,7.936884,649.089618,-3654.0,-521.0,-157.0,0.0,157.0,534.0,...,32767.0,10.939634,1279.909391,-13017.0,-976.0,-298.0,0.0,294.0,984.0,14873.0
4428,694853998,31206935,1.420993,110.942596,-753.0,-87.0,-25.0,0.0,27.0,90.0,...,897.0,-1.550374,251.560198,-1708.0,-187.0,-56.0,0.0,56.0,184.0,1549.0
4429,1886987043,9598270,0.905818,478.852581,-3555.0,-354.0,-105.0,0.0,105.0,354.0,...,2015.0,-6.360564,618.914657,-3588.0,-501.0,-153.0,0.0,145.0,490.0,3628.0
4430,1100632800,20128938,-4.142848,272.632730,-1404.0,-224.0,-66.0,0.0,63.0,207.0,...,1416.0,-45.584790,773.808829,-4007.0,-632.0,-173.0,0.0,170.0,561.0,3720.0

In [15]:
data_train = data.copy()
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4431 entries, 0 to 4430
Data columns (total 92 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   segment_id        4431 non-null   int64
 1   time_to_eruption  4431 non-null   int64
 2   sensor_1_mean     4431 non-null   float64
 3   sensor_1_std      4431 non-null   float64
 4   sensor_1_min      4431 non-null   float64
 5   sensor_1_20       4431 non-null   float64
 6   sensor_1_40       4431 non-null   float64
 7   sensor_1_50       4431 non-null   float64
 8   sensor_1_60       4431 non-null   float64
 9   sensor_1_80       4431 non-null   float64
 10  sensor_1_max      4431 non-null   float64
 11  sensor_2_mean     4431 non-null   float64
 12  sensor_2_std      4431 non-null   float64
 13  sensor_2_min      4431 non-null   float64
 14  sensor_2_20       4431 non-null   float64
 15  sensor_2_40       4431 non-null   float64
 16  sensor_2_50       4431 non-null   float64
 17  sensor_2_60       4431 non-null   float64
 18  sensor_2_80       4431 non-null   float64
 19  sensor_2_max      4431 non-null   float64
 20  sensor_3_mean     4431 non-null   float64
 21  sensor_3_std      4431 non-null   float64
 22  sensor_3_min      4431 non-null   float64
 23  sensor_3_20       4431 non-null   float64
 24  sensor_3_40       4431 non-null   float64
 25  sensor_3_50       4431 non-null   float64
 26  sensor_3_60       4431 non-null   float64
 27  sensor_3_80       4431 non-null   float64
 28  sensor_3_max      4431 non-null   float64
 29  sensor_4_mean     4431 non-null   float64
 30  sensor_4_std      4431 non-null   float64
 31  sensor_4_min      4431 non-null   float64
 32  sensor_4_20       4431 non-null   float64
 33  sensor_4_40       4431 non-null   float64
 34  sensor_4_50       4431 non-null   float64
 35  sensor_4_60       4431 non-null   float64
 36  sensor_4_80       4431 non-null   float64
 37  sensor_4_max      4431 non-null   float64
 38  sensor_5_mean     4431 non-null   float64
 39  sensor_5_std      4431 non-null   float64
 40  sensor_5_min      4431 non-null   float64
 41  sensor_5_20       4431 non-null   float64
 42  sensor_5_40       4431 non-null   float64
 43  sensor_5_50       4431 non-null   float64
 44  sensor_5_60       4431 non-null   float64
 45  sensor_5_80       4431 non-null   float64
 46  sensor_5_max      4431 non-null   float64
 47  sensor_6_mean     4431 non-null   float64
 48  sensor_6_std      4431 non-null   float64
 49  sensor_6_min      4431 non-null   float64
 50  sensor_6_20       4431 non-null   float64
 51  sensor_6_40       4431 non-null   float64
 52  sensor_6_50       4431 non-null   float64
 53  sensor_6_60       4431 non-null   float64
 54  sensor_6_80       4431 non-null   float64
 55  sensor_6_max      4431 non-null   float64
 56  sensor_7_mean     4431 non-null   float64
 57  sensor_7_std      4431 non-null   float64
 58  sensor_7_min      4431 non-null   float64
 59  sensor_7_20       4431 non-null   float64
 60  sensor_7_40       4431 non-null   float64
 61  sensor_7_50       4431 non-null   float64
 62  sensor_7_60       4431 non-null   float64
 63  sensor_7_80       4431 non-null   float64
 64  sensor_7_max      4431 non-null   float64
 65  sensor_8_mean     4431 non-null   float64
 66  sensor_8_std      4431 non-null   float64
 67  sensor_8_min      4431 non-null   float64
 68  sensor_8_20       4431 non-null   float64
 69  sensor_8_40       4431 non-null   float64
 70  sensor_8_50       4431 non-null   float64
 71  sensor_8_60       4431 non-null   float64
 72  sensor_8_80       4431 non-null   float64
 73  sensor_8_max      4431 non-null   float64
 74  sensor_9_mean     4431 non-null   float64
 75  sensor_9_std      4431 non-null   float64
 76  sensor_9_min      4431 non-null   float64
 77  sensor_9_20       4431 non-null   float64
 78  sensor_9_40       4431 non-null   float64
 79  sensor_9_50       4431 non-null   float64
 80  sensor_9_60       4431 non-null   float64
 81  sensor_9_80       4431 non-null   float64
 82  sensor_9_max      4431 non-null   float64
 83  sensor_10_mean    4431 non-null   float64
 84  sensor_10_std     4431 non-null   float64
 85  sensor_10_min     4431 non-null   float64
 86  sensor_10_20      4431 non-null   float64
 87  sensor_10_40      4431 non-null   float64
 88  sensor_10_50      4431 non-null   float64
 89  sensor_10_60      4431 non-null   float64
 90  sensor_10_80      4431 non-null   float64
 91  sensor_10_max     4431 non-null   float64
dtypes: float64(90), int64(2)
memory usage: 3.1 MB

In [16]:
data_train.describe()

,segment_id,time_to_eruption,sensor_1_mean,sensor_1_std,sensor_1_min,sensor_1_20,sensor_1_40,sensor_1_50,sensor_1_60,sensor_1_80,...,sensor_9_max,sensor_10_mean,sensor_10_std,sensor_10_min,sensor_10_20,sensor_10_40,sensor_10_50,sensor_10_60,sensor_10_80,sensor_10_max
count,4.431000e+03,4.431000e+03,4431.000000,4431.000000,4431.000000,4431.000000,4431.000000,4431.0,4431.000000,4431.000000,...,4431.000000,4431.000000,4431.000000,4431.000000,4431.000000,4431.000000,4431.0,4431.000000,4431.000000,4431.00000
mean,1.074694e+09,2.284891e+07,-0.524638,651.842101,-3147.202663,-517.972783,-153.569849,0.0,153.458136,516.181268,...,3104.505304,-0.362546,1058.606440,-5248.341458,-839.564794,-249.027353,0.0,249.135003,839.474791,5228.43963
std,6.161966e+08,1.348439e+07,17.911542,1516.321117,4831.281103,1298.842149,383.904517,0.0,385.162669,1290.717383,...,4878.327023,34.567683,1816.124986,5208.346859,1617.070949,478.790828,0.0,481.223622,1615.236085,5172.18309
min,5.131810e+05,6.250000e+03,-595.472192,0.000000,-32767.000000,-21859.000000,-6347.000000,0.0,0.000000,0.000000,...,0.000000,-1219.251543,0.000000,-32767.000000,-27068.000000,-8323.000000,0.0,0.000000,0.000000,0.00000
25%,5.527934e+08,1.127016e+07,-1.788295,275.012918,-2748.000000,-435.500000,-129.000000,0.0,63.000000,215.000000,...,1465.000000,-3.330541,581.878557,-5159.000000,-768.000000,-227.000000,0.0,129.000000,438.000000,3111.00000
50%,1.066153e+09,2.246559e+07,0.017700,361.358555,-1970.000000,-286.000000,-84.000000,0.0,85.000000,286.000000,...,2002.000000,0.097682,723.271700,-4115.000000,-567.000000,-169.000000,0.0,168.000000,568.000000,4074.00000
75%,1.606350e+09,3.434356e+07,1.826045,546.627936,-1389.500000,-216.000000,-63.000000,0.0,129.000000,437.500000,...,2775.500000,3.804481,979.230561,-3097.500000,-439.000000,-130.000000,0.0,228.000000,772.000000,5161.00000
max,2.146939e+09,4.904609e+07,341.221530,21182.637579,0.000000,0.000000,0.000000,0.0,6410.000000,21640.000000,...,32767.000000,1022.320278,23445.310398,0.000000,0.000000,0.000000,0.0,8918.000000,26489.000000,32767.00000

In [17]:
data_train.shape

(4431, 92)

In [18]:
time_to_eruption = data_train['time_to_eruption']
segment_id = data_train['segment_id']
data_train.drop(['time_to_eruption','segment_id'],axis = 1 , inplace=True)

In [20]:
data_train.describe()

,sensor_1_mean,sensor_1_std,sensor_1_min,sensor_1_20,sensor_1_40,sensor_1_50,sensor_1_60,sensor_1_80,sensor_1_max,sensor_2_mean,...,sensor_9_max,sensor_10_mean,sensor_10_std,sensor_10_min,sensor_10_20,sensor_10_40,sensor_10_50,sensor_10_60,sensor_10_80,sensor_10_max
count,4431.000000,4431.000000,4431.000000,4431.000000,4431.000000,4431.0,4431.000000,4431.000000,4431.000000,4431.000000,...,4431.000000,4431.000000,4431.000000,4431.000000,4431.000000,4431.000000,4431.0,4431.000000,4431.000000,4431.00000
mean,-0.524638,651.842101,-3147.202663,-517.972783,-153.569849,0.0,153.458136,516.181268,3183.427894,1.159530,...,3104.505304,-0.362546,1058.606440,-5248.341458,-839.564794,-249.027353,0.0,249.135003,839.474791,5228.43963
std,17.911542,1516.321117,4831.281103,1298.842149,383.904517,0.0,385.162669,1290.717383,4893.656332,71.598229,...,4878.327023,34.567683,1816.124986,5208.346859,1617.070949,478.790828,0.0,481.223622,1615.236085,5172.18309
min,-595.472192,0.000000,-32767.000000,-21859.000000,-6347.000000,0.0,0.000000,0.000000,0.000000,-245.220530,...,0.000000,-1219.251543,0.000000,-32767.000000,-27068.000000,-8323.000000,0.0,0.000000,0.000000,0.00000
25%,-1.788295,275.012918,-2748.000000,-435.500000,-129.000000,0.0,63.000000,215.000000,1402.000000,-1.431743,...,1465.000000,-3.330541,581.878557,-5159.000000,-768.000000,-227.000000,0.0,129.000000,438.000000,3111.00000
50%,0.017700,361.358555,-1970.000000,-286.000000,-84.000000,0.0,85.000000,286.000000,1974.000000,0.000000,...,2002.000000,0.097682,723.271700,-4115.000000,-567.000000,-169.000000,0.0,168.000000,568.000000,4074.00000
75%,1.826045,546.627936,-1389.500000,-216.000000,-63.000000,0.0,129.000000,437.500000,2799.500000,1.393618,...,2775.500000,3.804481,979.230561,-3097.500000,-439.000000,-130.000000,0.0,228.000000,772.000000,5161.00000
max,341.221530,21182.637579,0.000000,0.000000,0.000000,0.0,6410.000000,21640.000000,32767.000000,4489.707085,...,32767.000000,1022.320278,23445.310398,0.000000,0.000000,0.000000,0.0,8918.000000,26489.000000,32767.00000

In [21]:
# finding and removing constant columns
cols = []
for i in data_train.columns :
    if data_train[i].min() == data_train[i].max():
        cols.append(i)
cols

['sensor_1_50',
 'sensor_2_50',
 'sensor_3_50',
 'sensor_4_50',
 'sensor_5_50',
 'sensor_6_50',
 'sensor_7_50',
 'sensor_8_50',
 'sensor_9_50',
 'sensor_10_50']

In [22]:
#drop constant col

data_train.drop(['sensor_1_50', 'sensor_2_50', 'sensor_3_50','sensor_4_50', 'sensor_5_50', 'sensor_6_50',
                 'sensor_7_50', 'sensor_8_50', 'sensor_9_50', 'sensor_10_50'],axis = 1 , inplace=True)

In [23]:
data_train.shape

(4431, 80)

In [26]:
data_train

,sensor_1_mean,sensor_1_std,sensor_1_min,sensor_1_20,sensor_1_40,sensor_1_60,sensor_1_80,sensor_1_max,sensor_2_mean,sensor_2_std,...,sensor_9_80,sensor_9_max,sensor_10_mean,sensor_10_std,sensor_10_min,sensor_10_20,sensor_10_40,sensor_10_60,sensor_10_80,sensor_10_max
0,-1.610323,303.096099,-1421.0,-249.0,-72.0,72.0,249.0,1353.0,4.613823,678.330828,...,306.0,2021.0,2.599440,596.865818,-3527.0,-503.0,-151.0,159.0,507.0,2187.0
1,1.426126,438.360560,-2005.0,-333.0,-96.0,100.0,338.0,2197.0,2.484442,661.163255,...,321.6,2189.0,19.895518,932.699662,-4591.0,-692.0,-202.0,205.0,710.0,5319.0
2,2.504592,241.575415,-1115.0,-195.0,-58.0,58.0,199.0,1148.0,5.449709,831.469221,...,199.0,1778.0,0.968101,500.544892,-2798.0,-402.0,-121.0,120.0,403.0,2522.0
3,2.165797,221.967825,-1025.0,-171.0,-50.0,52.0,177.0,1254.0,-0.373377,425.189594,...,189.0,1340.0,8.381444,523.449843,-2911.0,-400.0,-121.0,122.0,407.0,3614.0
4,0.073815,261.695935,-1190.0,-216.0,-63.0,62.0,212.0,1114.0,0.000000,0.000000,...,212.0,7725.0,-3.740471,562.748316,-2611.0,-458.0,-134.0,134.0,449.0,3274.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4426,0.906735,613.427301,-2610.0,-511.0,-155.0,155.0,518.0,2916.0,-3.658256,940.746578,...,471.0,3085.0,-3.377394,1053.539787,-5726.0,-839.0,-249.0,240.0,838.0,5493.0
4427,7.936884,649.089618,-3654.0,-521.0,-157.0,157.0,534.0,4498.0,0.000000,0.000000,...,623.0,32767.0,10.939634,1279.909391,-13017.0,-976.0,-298.0,294.0,984.0,14873.0
4428,1.420993,110.942596,-753.0,-87.0,-25.0,27.0,90.0,557.0,0.446893,505.722491,...,103.0,897.0,-1.550374,251.560198,-1708.0,-187.0,-56.0,56.0,184.0,1549.0
4429,0.905818,478.852581,-3555.0,-354.0,-105.0,105.0,354.0,3938.0,0.000000,0.000000,...,227.0,2015.0,-6.360564,618.914657,-3588.0,-501.0,-153.0,145.0,490.0,3628.0
4430,-4.142848,272.632730,-1404.0,-224.0,-66.0,63.0,207.0,2063.0,0.138031,433.350044,...,192.0,1416.0,-45.584790,773.808829,-4007.0,-632.0,-173.0,170.0,561.0,3720.0